# Everything in this section will be available as an environment variable

CLIENT_ID = "0be1da36f0594963b21a361ae5bd5d07"
CLIENT_SECRET = "093f6e330b414e4cbda05e95dbc0bef7"
AWS_Service = 's3'
AWS_S3_bucket_name = 'dcsc-spotify'
AWS_Access_key = 'AKIA2QMVGA2J4I2JXQ3D'
AWS_Secret_Access_key = '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'
AWS_User = 's3_user'
AWS_FOLDER = 'Extract'
BUCKET_NAME = "AWS_S3_bucket_name"